"""empty message

Revision ID: 5027e1e91936
Revises: 7205816877ec
Create Date: 2024-09-09 07:49:06.723857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5027e1e91936'
down_revision = '7205816877ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('configurations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'configurations')
    # ### end Alembic commands ###
